version: "2"
services:
  owncloud:
    image: owncloud:10.0.10
    container_name: owncloud
    restart: always
    volumes:
     - /local/data/owncloud/config:/var/www/html/config:rw
     - /local/data/owncloud/data:/var/www/html/data:rw
     - /local/data/owncloud/apps:/var/www/html/apps:rw

  owncloud-db:
    image: postgres:9.6
    container_name: owncloud-db
    restart: always
    environment:
     - POSTGRES_PASSWORD=${OWNCLOUD_DB_PASSWORD}
    volumes:
     - /local/data/owncloud-db:/var/lib/postgresql/data:rw

networks:
  default:
    external:
      name: isaac   
